### ISSUE TITLE
Stairs

### ISSUE THREAD

**Issue by OrangeMann** [mattroks101/InterBay#100]
I believe stairs just missing some check for objects, because mobs can be pulled, grabbed, or else on it.
But any other object in the game can't be pulled on them. Correct me if i'm wrong.

**Comment by mattroks101** [comment]
Mobs can't be "pulled" on it. It does the same thing to mobs that it does to other objects. You have to grab a mob or zig zag to pull them up stairs.

**Comment by OrangeMann** [comment]
Well
