### ISSUE TITLE
Different kinds of knives

### ISSUE THREAD

**Issue by AndySok** [mattroks101/InterBay#11]
Baystation created two types of knives: "Steel Knives" and "Steel Kitchen Knives".

While you can put normal steel knives in your pockets, you cannot use them to use it on food(ex. meat). On the other hand, Kitchen Knives are able to manipulate food but you cannot put them inside a pocket.

The thing is that the have the **same sprite**.
(Steel Knife)
![image](https://user-images.githubusercontent.com/19246179/29348564-9e960132-8222-11e7-9f02-6935227ce312.png)

(Steel Kitchen Knife)
![image](https://user-images.githubusercontent.com/19246179/29348576-b23a76a0-8222-11e7-94ff-942c36e251b7.png)

**Comment by kyrahabattoir** [comment]
I actually haven't managed to cut cheese with the steel kitchen knife either.

The way bay appears to do things is that items are given a material property at runtime.

Two easy ways to solve this:
1. Use the steel kitchen knife, and use plastic utensils for the others (which kinda makes sense).
2. Replace the kitchen knife by the cleaver, but it's an even better weapon.

Both would be a stopgap solution until they are sprited differently.

**Comment by kyrahabattoir** [comment]
To be honest I'm a little annoyed that sliceable objects seem to support both the behavior of hiding a blade inside them, and SOME blades being able to slice it.

If anything it's a bit inconsistent.

**Comment by kyrahabattoir** [comment]
There you go.

https://github.com/mattroks101/InterBay/pull/38
