### ISSUE TITLE
[Map]Utopia Kitchen needs a few small things.

### ISSUE THREAD

**Issue by kyrahabattoir** [mattroks101/InterBay#112]
~~There is a meat grinder but that's not replacing the processor.~~
* Kitchen needs an /obj/machinery/hotplate 
* The bar a /obj/machinery/hotplate/chiller .
* The cookbook need to be replaced by /obj/item/weapon/book/rpbook/cooking_basic
* A sink because running to the toilets or botany to make dough is unrealistic.

**Comment by OrangeMann** [comment]
Done
