### ISSUE TITLE
Mood boost for Inquisitors that got rid of heretic

### ISSUE THREAD

**Issue by OrangeMann** [mattroks101/InterBay#135]
And maybe also negative mood for seeing one not yet decapitated?

**Comment by kyrahabattoir** [comment]
Rid, or applied a suitable treatment to a heretic?

might have to be delayed or require the validation of the computer to prevent people using branding/torture as an aternative to revelator.

**Comment by mattroks101** [comment]
If you brand one you already get a good mood, and you get a good mood every time you see a branded on too. In turn they get a bad mood when you look upon them.
