### ISSUE TITLE
[Suggestion] If you get hurt while you typing something in ic, it will automatically be sent in that state into chat.

### ISSUE THREAD

**Issue by OrangeMann** [mattroks101/InterBay#141]
And when i'm saying "hurt" i mean if someone tries to beat the shit out of you, some internal pain should not do that.

**Comment by kachnov** [comment]
Do any other servers have this? I wonder if its even possible considering how BYOND input code works

**Comment by kyrahabattoir** [comment]
I don't think it's possible, judging from how input() works.

**Comment by mattroks101** [comment]
It does that already. They just have to be using non hotkey mode for it to happen. If you're in hotkey mode it doesn't do that.

**Comment by OrangeMann** [comment]
Well crap

**Comment by mattroks101** [comment]
This is already a thing so I'm closing it.
