### ISSUE TITLE
Problems with sides in damage zone

### ISSUE THREAD

**Issue by joctopus** [mattroks101/InterBay#26]
![1 screenshot](https://media.discordapp.net/attachments/258237777236197378/350253528222269450/unknown.png)
![2 screenshot](https://media.discordapp.net/attachments/258237777236197378/350253571759013888/unknown.png)
also it's trouble with hands

**Comment by mattroks101** [comment]
Not explicitly a glitch but this does cause confusion. I'll update the sprite to be less confusing.
