### ISSUE TITLE
Hardsuit modules/attachments do not respond or interact properly

### ISSUE THREAD

**Issue by martinlyra** [mattroks101/InterBay#34]
So far I've tested, only the passive and toggle-active modules function properly. Meanwhile active (Ctrl/Alt/MMB-clicking) do not respond or interact properly with doors or walls. The mounted RCD will often complain about insufficient resources, even on deconstruction mode.

**Comment by mattroks101** [comment]
Most likely due to the jump and kick. Need to look deeper into click code.

**Comment by kyrahabattoir** [comment]
Is there no way we could have simple space suits instead? I mean if you like those space rigs that's okay but it seems needlessly complicated.

**Comment by mattroks101** [comment]
Honestly simple hardsuits/softsuits are what I'm planning on replacing these with. They're in the code. Just not the current map.

**Comment by mattroks101** [comment]
Hardsuits have been removed. I'm going to close this issue but this problem has not been resolved code wise.
