### ISSUE TITLE
Possible hotkey conflicts

### ISSUE THREAD

**Issue by kyrahabattoir** [mattroks101/InterBay#46]
I'm not entirely sure what the deal is but while wearing a space suit, some of the hotkeys (switch hands/drop/throw or something) are replaced by something else.

**Comment by mattroks101** [comment]
What are they replaced with?

**Comment by kyrahabattoir** [comment]
Some kind of jumping mechanic I think?

I only saw the messages while i was inside the station and they just said i hit the ceiling/floor.

**Comment by kyrahabattoir** [comment]
Update on this it also happens when you wear a radiation suit, pageup/pagedown try to make you ascend/descend Z levels i believe, like if you where in space, or something.

**Comment by kyrahabattoir** [comment]
I believe the problem is related to:
```
\code\modules\mob\living\carbon\human\human_helpers.dm:
   16  			to_chat(src, "Where do you intend to put \the [food]? You don't have a mouth!")
   17  		else if(status[1] == HUMAN_EATING_BLOCKED_MOUTH)
   18: 			to_chat(src, "<span class='warning'>\The [status[2]] is in the way!</span>")
   19  	return 0
   20  
   ..
   27  			to_chat(feeder, "Where do you intend to put \the [food]? \The [src] doesn't have a mouth!")
   28  		else if(status[1] == HUMAN_EATING_BLOCKED_MOUTH)
   29: 			to_chat(feeder, "<span class='warning'>\The [status[2]] is in the way!</span>")
   30  	return 0
   31  
```

**Comment by OrangeMann** [comment]
That's because the multi-z movement was on "<" ">" keys, someone changed it luna-like ones, don't remember who did that.

**Comment by athompson11** [comment]
Not an issue.
`	var/hotkey_mode = {"<font color='purple'>
Hotkey-Mode: (hotkey-mode must be on)
\tTAB = toggle hotkey-mode
\ta = left
\ts = down
\td = right
\tw = up
\tq = drop
\te = equip
\tr = throw
\tt = say
\t5 = emote
\tx = swap-hand
\tz = activate held object (or y)
\tj = toggle-aiming-mode
\tf = cycle-intents-left
\tg = cycle-intents-right
\t1 = help-intent
\t2 = disarm-intent
\t3 = grab-intent
\t4 = harm-intent
\tCtrl = drag
\tShift = examine
\tPGUP = Move upwards
\tPGDOWN = Move downwards
</font>"}

	var/other = {"<font color='purple'>
Any-Mode: (hotkey doesn't need to be on)
\tCtrl+a = left
\tCtrl+s = down
\tCtrl+d = right
\tCtrl+w = up
\tCtrl+q = drop
\tCtrl+e = equip
\tCtrl+r = throw
\tCtrl+x = swap-hand
\tCtrl+z = activate held object (or Ctrl+y)
\tCtrl+f = cycle-intents-left
\tCtrl+g = cycle-intents-right
\tCtrl+1 = help-intent
\tCtrl+2 = disarm-intent
\tCtrl+3 = grab-intent
\tCtrl+4 = harm-intent
\tF1 = adminhelp
\tF2 = ooc
\tF3 = say
\tF4 = emote
\tDEL = pull
\tINS = cycle-intents-right
\tHOME = drop
\tPGUP = swap-hand
\tPGDN = activate held object
\tEND = throw
</font>"}`
To cycle your hands, turn off hotkey mode then press the correct button.

**Comment by kyrahabattoir** [comment]
Then we should move ascend/descend somewhere else.

**Comment by OrangeMann** [comment]
Just swap x with hands man, what's wrong.

**Comment by kyrahabattoir** [comment]
I DONT USE WASD I HAVE A FRENCH KEYBOARD YOU CUCK

**Comment by OrangeMann** [comment]
Use them then
