### ISSUE TITLE
Utopia: Not enough power at round start

### ISSUE THREAD

**Issue by kyrahabattoir** [mattroks101/InterBay#84]
There is simply not enough power in the station at round start.

Now that I had to try teaching people how to run the engine:

* There is barely enough time for someone who knows what they are doing to do the start sequence.
* Engineering needs a dedicated SMES, the engine machineries use about 50-70kW and will empty the APC in less than a minute.
* The single SMES at the engine output is such a bottleneck that anyone playing engineer will just end up rewiring the 3 SMES in paralelle every round.

Seriously i thought this would be fine (being a former tg player) but there is a reason most bay maps have SMES  on multiple floors, the power stored in APCs is nowhere nearly as useful as it would be on TG because all machines use power on Interbay, a lot of it.

How to fix it:
* Wire the 3 engineering SMES directly in the engine, it's not worth the complication of cascading them.
* Add an SMES  to Zlevel-3, medbay, security and command shouldn't be the first thing to go when the station goes to shit.

**Comment by mattroks101** [comment]
Pretty sure this has been fixed in the latest map updates.

**Comment by OrangeMann** [comment]
Okay you mean that because apc of engine itself getting juice before two SMES, he will get out of it very fast right? Maybe i'll just get it to upper floor then.

**Comment by mattroks101** [comment]
I haven't encountered power going out super fast since the latest map update.

**Comment by OrangeMann** [comment]
Power going out super fast for engine room apc.

**Comment by mattroks101** [comment]
Hmm

**Comment by OrangeMann** [comment]
Maybe put apc before all SMES so it will get power exclusive from solars? so wiring them actually needed.

**Comment by OrangeMann** [comment]
It actually has Pacman as well, so it's not that bad feature.

**Comment by kyrahabattoir** [comment]
Why do you absolutely not want to start the round with all SMES full and all APCs full?

**Comment by OrangeMann** [comment]
Because that's gay.

**Comment by OrangeMann** [comment]
You either start with engineers or git fukt, actually last updates fixed most issues with that tho.
I mean, you will be able to start engine at any conditions

**Comment by kyrahabattoir** [comment]
When was the last time you played the map with other players?

**Comment by OrangeMann** [comment]
You will not.

**Comment by OrangeMann** [comment]
It's so easy to get engine up at this point, and you still complaining.

**Comment by kyrahabattoir** [comment]
I've has to cover as engineer every single round as engineer since utopia went live and any round i'm not the admins end up using the smes powerup secret.

**Comment by OrangeMann** [comment]
I'll get today as upkeeper to prove or disprove my point then.

**Comment by kyrahabattoir** [comment]
Today is tuesday, wait for the weekend if anything.

**Comment by OrangeMann** [comment]
So i guess i'll just get to play it with my friends and see what they think.

**Comment by kyrahabattoir** [comment]
I'll consider it fixed i guess.
