### ISSUE TITLE
Mapping Error: Kitchen Backroom

### ISSUE THREAD

**Issue by Pawoverlord** [mattroks101/InterBay#90]
#### Description of issue

The knife and rolling pin in this image is in a place that is impossible for anyone to access without moving the backroom around. The oven and the condimaster are impassable objects.
[](https://gyazo.com/e26ef79bcf90ee5f009475d7accd1716)

#### Difference between expected and actual behavior

I believe the chef could use the rolling pin to produce more foods aboard the station.

#### Steps to reproduce 

Spawn in, head to the kitchen backroom and attempt to grab the rolling pin or knife. 

#### Specific information for locating

[](https://gyazo.com/e26ef79bcf90ee5f009475d7accd1716)

#### Length of time in which bug has been known to occur

Assumed to be around since mapped in.

#### Client version, Server revision & Game ID

Recent. (10/25/2017)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/mattroks101/InterBay/issues)

**Comment by OrangeMann** [comment]
Yeah well that's mistake i made because i didn't touched kitchen for a while, wait for that one to be fixed.

**Comment by mattroks101** [comment]
Fixed as of latest map update.
