### ISSUE TITLE
Radio Say

### ISSUE THREAD

**Issue by OrangeMann** [mattroks101/InterBay#95]
For some reason my say stuff appears with 30 seconds latency if i'm trying to put that in radio channel, but if i'm not it's working same as usual, don't know how that happen tho, maybe lung rupture is something to do with that.

**Comment by OrangeMann** [comment]
Or with pain, i got this stuff only after moderate pain or something.

**Comment by Naxodile** [comment]
Not a bug, telecomms overheats on utopia since it lacks any cooling at all.

**Comment by Naxodile** [comment]
In addition telecomms uses _airless_ tiles for some insane reason. Which makes heating to shutdown very quick. Replace them with server tiles or add a cooling system and you'll be fine.

**Comment by OrangeMann** [comment]
That's not the case, entire message is not sending out for 30, not only radio part of it.

**Comment by OrangeMann** [comment]
Even tho, bay's telecomms don't even need cooling, i have checked the torch map.

**Comment by OrangeMann** [comment]
But they could need air

**Comment by mattroks101** [comment]
Pretty sure Nax knows what they're talking about Orange. Regardless of whether or not that is causing the bug you have made an error in mapping telecoms.

**Comment by OrangeMann** [comment]
I'll check that
